version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run:
          name: Build and Test with Maven
          command: mvn clean verify
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master

